.PHONY: clean All

All:
	@echo "----------Building project:[ SuryasProgramma - Debug ]----------"
	@cd "C:\Programming\Surya\SuryasProgramma" && $(MAKE) -f  "SuryasProgramma.mk"
clean:
	@echo "----------Cleaning project:[ SuryasProgramma - Debug ]----------"
	@cd "C:\Programming\Surya\SuryasProgramma" && $(MAKE) -f  "SuryasProgramma.mk" clean
